/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Image;
import java.io.File;
import java.util.Date;
import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.filechooser.FileNameExtensionFilter;
import model.EmployeeProfile;
import model.EmployeeProfileHistory;

/**
 *
 * @author bhargavi
 */
public class CreateJPanel extends javax.swing.JPanel {

    /**
     * Creates new form CreateJPane
     */
    EmployeeProfileHistory profileHistory; //this will store reference
    
    public String imagePath;
    public String genderRadioButton;
    public String checkError;
    
    public CreateJPanel(EmployeeProfileHistory profileHistory) {
        
        initComponents();
        this.profileHistory = profileHistory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        lblTitle = new javax.swing.JLabel();
        lblEmployeeName = new javax.swing.JLabel();
        lblEmployeeId = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblStartDate = new javax.swing.JLabel();
        lblLevel = new javax.swing.JLabel();
        lblTeamInfo = new javax.swing.JLabel();
        lblPositionTitle = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblPhoto = new javax.swing.JLabel();
        txtEmployeeName = new javax.swing.JTextField();
        txtEmployeeId = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtLevel = new javax.swing.JTextField();
        txtTeamInfo = new javax.swing.JTextField();
        txtPositionTitle = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        btnSave = new javax.swing.JButton();
        lblei = new javax.swing.JLabel();
        lbla = new javax.swing.JLabel();
        lblg = new javax.swing.JLabel();
        lblen = new javax.swing.JLabel();
        lblsd = new javax.swing.JLabel();
        lbll = new javax.swing.JLabel();
        lblpt = new javax.swing.JLabel();
        lblti = new javax.swing.JLabel();
        lblp = new javax.swing.JLabel();
        lble = new javax.swing.JLabel();
        lblPhotoDisplay = new javax.swing.JLabel();
        btnBrowse = new javax.swing.JButton();
        rbtnFemale = new javax.swing.JRadioButton();
        rbtnMale = new javax.swing.JRadioButton();
        jdcCalendar = new com.toedter.calendar.JDateChooser();

        setPreferredSize(new java.awt.Dimension(800, 400));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        lblTitle.setFont(new java.awt.Font("Times New Roman", 1, 18)); // NOI18N
        lblTitle.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblTitle.setText("Create Employee Profile");
        add(lblTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 6, 800, 32));

        lblEmployeeName.setText("Employee Name :");
        add(lblEmployeeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(15, 68, -1, -1));

        lblEmployeeId.setText("Employee ID :");
        add(lblEmployeeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(37, 129, -1, -1));

        lblAge.setText("Age :");
        add(lblAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(89, 185, -1, -1));

        lblGender.setText("Gender :");
        add(lblGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(68, 249, -1, -1));

        lblStartDate.setText("Start Date :");
        add(lblStartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(422, 68, -1, -1));

        lblLevel.setText("Level :");
        add(lblLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(449, 121, -1, -1));

        lblTeamInfo.setText("Team Info :");
        add(lblTeamInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(423, 185, -1, -1));

        lblPositionTitle.setText("Position Title :");
        add(lblPositionTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(406, 249, -1, -1));

        lblPhone.setText("Phone :");
        add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 302, -1, -1));

        lblEmail.setText("E-mail :");
        add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(75, 360, -1, -1));

        lblPhoto.setText("Photo :");
        add(lblPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(447, 328, -1, -1));

        txtEmployeeName.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeNameActionPerformed(evt);
            }
        });
        txtEmployeeName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmployeeNameKeyReleased(evt);
            }
        });
        add(txtEmployeeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 65, 204, -1));

        txtEmployeeId.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmployeeIdKeyReleased(evt);
            }
        });
        add(txtEmployeeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 126, 204, -1));

        txtAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtAgeKeyReleased(evt);
            }
        });
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 182, 204, -1));

        txtLevel.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtLevelKeyReleased(evt);
            }
        });
        add(txtLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 118, 204, 24));

        txtTeamInfo.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtTeamInfoKeyReleased(evt);
            }
        });
        add(txtTeamInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 181, 204, 25));

        txtPositionTitle.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPositionTitleKeyReleased(evt);
            }
        });
        add(txtPositionTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 241, 204, -1));

        txtPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtPhoneKeyReleased(evt);
            }
        });
        add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 299, 204, -1));

        txtEmail.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtEmailKeyReleased(evt);
            }
        });
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 357, 204, -1));

        btnSave.setText("Save");
        btnSave.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnSaveActionPerformed(evt);
            }
        });
        add(btnSave, new org.netbeans.lib.awtextra.AbsoluteConstraints(287, 449, -1, -1));
        add(lblei, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 155, 204, 23));
        add(lbla, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 212, 204, 23));
        add(lblg, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 274, 204, 23));
        add(lblen, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 91, 204, 23));
        add(lblsd, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 91, 204, 23));
        add(lbll, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 155, 204, 23));
        add(lblpt, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 270, 204, 23));
        add(lblti, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 212, 204, 23));
        add(lblp, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 328, 204, 23));
        add(lble, new org.netbeans.lib.awtextra.AbsoluteConstraints(132, 386, 204, 23));
        add(lblPhotoDisplay, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 328, 114, 113));

        btnBrowse.setText("Browse");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });
        add(btnBrowse, new org.netbeans.lib.awtextra.AbsoluteConstraints(673, 354, -1, -1));

        rbtnFemale.setText("Female");
        rbtnFemale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnFemaleActionPerformed(evt);
            }
        });
        add(rbtnFemale, new org.netbeans.lib.awtextra.AbsoluteConstraints(131, 247, -1, -1));

        rbtnMale.setText("Male");
        rbtnMale.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                rbtnMaleActionPerformed(evt);
            }
        });
        add(rbtnMale, new org.netbeans.lib.awtextra.AbsoluteConstraints(202, 247, -1, -1));
        add(jdcCalendar, new org.netbeans.lib.awtextra.AbsoluteConstraints(547, 62, 204, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void btnSaveActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnSaveActionPerformed
        // TODO add your handling code here:
        
        if(checkError != null){
               JOptionPane.showMessageDialog(this,"Please provide valid inputs to all fields"); 

        }
        else{
        String name = txtEmployeeName.getText();
        String employeeId = txtEmployeeId.getText();
        int age = Integer.parseInt(txtAge.getText());
        String gender = genderRadioButton;
        long phone = Long.parseLong(txtPhone.getText());
        String email = txtEmail.getText();
        String positionTitle = txtPositionTitle.getText();
        String level = txtLevel.getText();
        Date startDate = jdcCalendar.getDate();
        String teamInfo = txtTeamInfo.getText();
        String photo = imagePath;
        
        EmployeeProfile ep = profileHistory.addNewProfile();
        
        // sets value to ArrayList from the fields that the data is entered.
        ep.setName(name);
        ep.setEmployeeId(employeeId);
        ep.setAge(age);
        ep.setPhone(phone);
        ep.setGender(gender);
        ep.setEmail(email);
        ep.setPositionTitle(positionTitle);
        ep.setStartDate(startDate);
        ep.setTeamInfo(teamInfo);
        ep.setLevel(level);
        ep.setPhoto(photo);
        
        // shows a dialogue message when the data clicked save button
        JOptionPane.showMessageDialog(this,"Employee details added"); 
        
        // empties all the fields after saving the entered data to ArrayList to facilitate new entries.
        txtEmployeeName.setText("");
        txtEmployeeId.setText("");
        txtAge.setText("");
        genderRadioButton = null; // making global variable null
        // unchecking radiobuttons by setting male and female to false
        rbtnMale.setSelected(false); 
        rbtnFemale.setSelected(false);
        txtEmail.setText("");
        txtPositionTitle.setText("");
        txtLevel.setText("");
        jdcCalendar.setDate(null);
        txtTeamInfo.setText("");
        txtPhone.setText("");
        lblPhoto.setText(null);
        }


    }//GEN-LAST:event_btnSaveActionPerformed

    private void txtEmployeeNameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeNameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeNameActionPerformed

    /**
     * validates employee name
     * shows message if invalid input entered
     * @param evt 
     */
    private void txtEmployeeNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmployeeNameKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z '/:]+$"; // regex that matches the input
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(txtEmployeeName.getText()); // gets text from field and matched against the regex
     
        if(!match.matches())
        {
            checkError = "error";
            lblen.setText("Enter a valid Input."); //throws message if input other than text is entered
        }
        else
        {
            checkError = null;
            lblen.setText(null);
        }
    }//GEN-LAST:event_txtEmployeeNameKeyReleased

    private void txtEmployeeIdKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmployeeIdKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeIdKeyReleased

    private void txtAgeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtAgeKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9 +()-]{1,3}$";  // pattern to check against input
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(txtAge.getText());
        if(!match.matches())
        {
            checkError = "error";
            lbla.setText("Enter Valid Age"); // throws error message
        }
        else
        {
            checkError = null;
            lbla.setText(null);
        }
    }//GEN-LAST:event_txtAgeKeyReleased

    private void txtLevelKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtLevelKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLevelKeyReleased

    private void txtTeamInfoKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtTeamInfoKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtTeamInfoKeyReleased

    private void txtPositionTitleKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPositionTitleKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_txtPositionTitleKeyReleased

    /**
     * validates phone number entered
     * throws error message if input other than numbers are entered
     * @param evt 
     */
    private void txtPhoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtPhoneKeyReleased
         //TODO add your handling code here:
        String PATTERN = "^[0-9 +()-]{10}$";  // pattern to check against input
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(txtPhone.getText());
        if(!match.matches())
        {
            checkError = "error";
            lblp.setText("Please Enter a 10 digit number."); // throws error message
        }
        else
        {
            checkError = null;
            lblp.setText(null);
        }
    }//GEN-LAST:event_txtPhoneKeyReleased

    /**
     * Email input validation
     * @param evt 
     */
    private void txtEmailKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtEmailKeyReleased
        // TODO add your handling code here:
         String PATTERN = "^[a-zA-Z0-9+_.-]+@[a-zA-Z0-9.-]+$"; // regex to be matched against input
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(txtEmail.getText());
        if(!match.matches())
        {
            checkError = "error";
            lble.setText("Wrong Input. Please Try Again.");
        }
        else
        {
            checkError = null;
            lble.setText(null);
        }
    }//GEN-LAST:event_txtEmailKeyReleased

    
    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        // TODO add your handling code here:
        JFileChooser browseImage = new JFileChooser();
        //Filter image extensions
        FileNameExtensionFilter filter = new FileNameExtensionFilter("IMAGES", "png", "jpg", "jpeg");
        // choosing image format files.
        browseImage.addChoosableFileFilter(filter);
        int showOpenDialogue = browseImage.showOpenDialog(null);
        if (showOpenDialogue == JFileChooser.APPROVE_OPTION)
        {
            File selectedImageFile = browseImage.getSelectedFile();
            String selectedImagePath = selectedImageFile.getAbsolutePath();
            JOptionPane.showMessageDialog(null, selectedImagePath);
            //Display image on jlable
            imagePath = selectedImagePath;
//            history.setPhoto(selectedImagePath);
            ImageIcon ii = new ImageIcon(selectedImagePath);
            //Resize image to fit jlabel
            Image image = ii.getImage().getScaledInstance(lblPhotoDisplay.getWidth(), lblPhotoDisplay.getHeight(), Image.SCALE_SMOOTH);
            lblPhotoDisplay.setIcon(new ImageIcon(image));
        }
    
    }//GEN-LAST:event_btnBrowseActionPerformed

    private void rbtnFemaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnFemaleActionPerformed
        // TODO add your handling code here:
        genderRadioButton ="Female"; // reassigning global variable
        rbtnMale.setSelected(false);
        rbtnFemale.setSelected(true);
    }//GEN-LAST:event_rbtnFemaleActionPerformed

    private void rbtnMaleActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_rbtnMaleActionPerformed
        // TODO add your handling code here:
        genderRadioButton ="Male";
        rbtnMale.setSelected(true);
        rbtnFemale.setSelected(false);
    }//GEN-LAST:event_rbtnMaleActionPerformed

    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnSave;
    private com.toedter.calendar.JDateChooser jdcCalendar;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmployeeId;
    private javax.swing.JLabel lblEmployeeName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPhoto;
    private javax.swing.JLabel lblPhotoDisplay;
    private javax.swing.JLabel lblPositionTitle;
    private javax.swing.JLabel lblStartDate;
    private javax.swing.JLabel lblTeamInfo;
    private javax.swing.JLabel lblTitle;
    private javax.swing.JLabel lbla;
    private javax.swing.JLabel lble;
    private javax.swing.JLabel lblei;
    private javax.swing.JLabel lblen;
    private javax.swing.JLabel lblg;
    private javax.swing.JLabel lbll;
    private javax.swing.JLabel lblp;
    private javax.swing.JLabel lblpt;
    private javax.swing.JLabel lblsd;
    private javax.swing.JLabel lblti;
    private javax.swing.JRadioButton rbtnFemale;
    private javax.swing.JRadioButton rbtnMale;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmployeeId;
    private javax.swing.JTextField txtEmployeeName;
    private javax.swing.JTextField txtLevel;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPositionTitle;
    private javax.swing.JTextField txtTeamInfo;
    // End of variables declaration//GEN-END:variables
}
