/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.awt.Image;
import java.io.File;
import java.util.Date;
import javax.swing.ImageIcon;
import javax.swing.JFileChooser;
import javax.swing.JOptionPane;
import javax.swing.RowFilter;
import javax.swing.filechooser.FileNameExtensionFilter;
import employeemodel.EmployeeProfileHistory;
import javax.swing.table.DefaultTableModel;
import javax.swing.table.TableRowSorter;
import employeemodel.EmployeeProfile;

/**
 *
 * @author  Venkata Bhargavi
 */
public class DisplayJPanel extends javax.swing.JPanel {

    
    EmployeeProfileHistory profileHistory;
    public String photo_Path;
    /**
     * Creates new form DisplayJPanel
     */
    public DisplayJPanel(EmployeeProfileHistory profileHistory) {
        initComponents();
        this.profileHistory  = profileHistory; // the reference of profileHistory from this function is stored in this.profileHistory which is declared above.
        populateDataToTable();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        displayTable = new javax.swing.JTable();
        btnview = new javax.swing.JButton();
        btnDelete = new javax.swing.JButton();
        lblEmployeeId = new javax.swing.JLabel();
        lblEmployeeName = new javax.swing.JLabel();
        lblAge = new javax.swing.JLabel();
        lblGender = new javax.swing.JLabel();
        lblPhone = new javax.swing.JLabel();
        lblEmail = new javax.swing.JLabel();
        lblStartDate = new javax.swing.JLabel();
        lblLevel = new javax.swing.JLabel();
        lblTeamInfo = new javax.swing.JLabel();
        lblPositionTitle = new javax.swing.JLabel();
        txtEmployeeId = new javax.swing.JTextField();
        txtEmployeeName = new javax.swing.JTextField();
        txtAge = new javax.swing.JTextField();
        txtGender = new javax.swing.JTextField();
        txtPhone = new javax.swing.JTextField();
        txtEmail = new javax.swing.JTextField();
        txtLevel = new javax.swing.JTextField();
        txtTeamInfo = new javax.swing.JTextField();
        txtPositionTitle = new javax.swing.JTextField();
        lblDisplayPhoto = new javax.swing.JLabel();
        btnUpdate = new javax.swing.JButton();
        lblSearch = new javax.swing.JLabel();
        txtSearch = new javax.swing.JTextField();
        btnBrowse = new javax.swing.JButton();
        jDateChooseSD = new com.toedter.calendar.JDateChooser();

        setPreferredSize(new java.awt.Dimension(1200, 1200));
        setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jLabel1.setFont(new java.awt.Font("Times New Roman", 1, 24)); // NOI18N
        jLabel1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        jLabel1.setText("Employee Details");
        add(jLabel1, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 30, 1200, -1));

        displayTable.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Employee ID", "Name", "Age", "Gender", "Phone", "E-mail", "Start Date", "Level", "Team Info", "Position Title"
            }
        ) {
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false, false, false, false, false, false
            };

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jScrollPane1.setViewportView(displayTable);

        add(jScrollPane1, new org.netbeans.lib.awtextra.AbsoluteConstraints(10, 110, 1170, 197));

        btnview.setText("View & Edit");
        btnview.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnviewActionPerformed(evt);
            }
        });
        add(btnview, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 330, -1, -1));

        btnDelete.setText("Delete");
        btnDelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnDeleteActionPerformed(evt);
            }
        });
        add(btnDelete, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 330, -1, -1));

        lblEmployeeId.setText("Employee Id");
        add(lblEmployeeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(50, 390, -1, -1));

        lblEmployeeName.setText("Employee Name");
        add(lblEmployeeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(30, 440, -1, -1));

        lblAge.setText("Age");
        add(lblAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 480, -1, -1));

        lblGender.setText("Gender");
        add(lblGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(80, 520, -1, -1));

        lblPhone.setText("Phone");
        add(lblPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(90, 560, -1, -1));

        lblEmail.setText("E-mail");
        add(lblEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 390, 74, -1));

        lblStartDate.setText("Start Date");
        add(lblStartDate, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 440, 74, -1));

        lblLevel.setText("Level");
        add(lblLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 480, 74, -1));

        lblTeamInfo.setText("Team Info");
        add(lblTeamInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 520, 74, -1));

        lblPositionTitle.setText("Position Title");
        add(lblPositionTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(630, 560, -1, -1));

        txtEmployeeId.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtEmployeeIdActionPerformed(evt);
            }
        });
        add(txtEmployeeId, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 390, 195, -1));
        add(txtEmployeeName, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 430, 195, -1));
        add(txtAge, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 470, 195, -1));
        add(txtGender, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 510, 195, -1));
        add(txtPhone, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 560, 195, -1));
        add(txtEmail, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 390, 195, -1));

        txtLevel.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtLevelActionPerformed(evt);
            }
        });
        add(txtLevel, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 470, 195, -1));
        add(txtTeamInfo, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 510, 195, -1));
        add(txtPositionTitle, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 560, 195, -1));
        add(lblDisplayPhoto, new org.netbeans.lib.awtextra.AbsoluteConstraints(410, 390, 150, 180));

        btnUpdate.setText("Update");
        btnUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnUpdateActionPerformed(evt);
            }
        });
        add(btnUpdate, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 640, -1, -1));

        lblSearch.setFont(new java.awt.Font("Helvetica Neue", 0, 14)); // NOI18N
        lblSearch.setText("Search");
        add(lblSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(40, 67, 50, 30));

        txtSearch.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtSearchKeyReleased(evt);
            }
        });
        add(txtSearch, new org.netbeans.lib.awtextra.AbsoluteConstraints(110, 70, 180, -1));

        btnBrowse.setText("Browse");
        btnBrowse.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnBrowseActionPerformed(evt);
            }
        });
        add(btnBrowse, new org.netbeans.lib.awtextra.AbsoluteConstraints(450, 580, -1, -1));
        add(jDateChooseSD, new org.netbeans.lib.awtextra.AbsoluteConstraints(790, 430, 200, -1));
    }// </editor-fold>//GEN-END:initComponents

    private void txtEmployeeIdActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtEmployeeIdActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtEmployeeIdActionPerformed

    private void txtLevelActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtLevelActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtLevelActionPerformed

    private void btnDeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnDeleteActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = displayTable.getSelectedRow();  // gives index of selected rows
        if(selectedRowIndex < 0)
        {
           JOptionPane.showMessageDialog(this, "Select a entry to delete");
           return;
        }
        
        DefaultTableModel model = (DefaultTableModel)displayTable.getModel();
        
        //DefaultTableModel model = (DefaultTableModel) displayTable.getModel();
        // getting reference of selected entry.
        EmployeeProfile selectedEntry = (EmployeeProfile) model.getValueAt(selectedRowIndex, 0);  // to get any value cells from table through row and column
            
        profileHistory.deleteProfile(selectedEntry);
        
        JOptionPane.showMessageDialog(this, "Selected Employee Deleted");
        
        populateDataToTable(); //  deletes record from table and updates all entries
        
        //once deleted all the fiels in view model will be deleted
          txtEmployeeId.setText("");
          txtAge.setText("");
          txtEmail.setText("");
          txtEmployeeName.setText("");
          txtGender.setText("");
          txtLevel.setText("");
          txtPhone.setText("");
          txtPositionTitle.setText("");
          jDateChooseSD.setDate(null);
          txtTeamInfo.setText(""); 
          lblDisplayPhoto.setIcon(null);

          
          
          
     
    }//GEN-LAST:event_btnDeleteActionPerformed

    private void btnviewActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnviewActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = displayTable.getSelectedRow();  // gives index of selected rows
        if(selectedRowIndex < 0)
        {
           JOptionPane.showMessageDialog(this, "Select a entry to view");
           return;
        }
        
        DefaultTableModel model = (DefaultTableModel)displayTable.getModel();
        
        //DefaultTableModel model = (DefaultTableModel) displayTable.getModel();
        // getting reference of selected entry.
        EmployeeProfile selectedEntry = (EmployeeProfile) model.getValueAt(selectedRowIndex, 0);  // to get any value cells from table through row and column
          txtEmployeeId.setText(selectedEntry.getEmployeeId());
          txtAge.setText(String.valueOf(selectedEntry.getAge()));
          txtEmail.setText(selectedEntry.getEmail());
          txtEmployeeName.setText(selectedEntry.getName());
          txtGender.setText(selectedEntry.getGender());
          txtLevel.setText(selectedEntry.getLevel());
          txtPhone.setText(String.valueOf(selectedEntry.getPhone()));
          txtPositionTitle.setText(selectedEntry.getPositionTitle());
          jDateChooseSD.setDate(selectedEntry.getStartDate());
          txtTeamInfo.setText(selectedEntry.getTeamInfo());

          
         ImageIcon ii = new ImageIcon(selectedEntry.getPhoto());
        Image image = ii.getImage().getScaledInstance(lblDisplayPhoto.getWidth(), lblDisplayPhoto.getHeight(), Image.SCALE_SMOOTH);
        lblDisplayPhoto.setIcon(new ImageIcon(image));

        
    }//GEN-LAST:event_btnviewActionPerformed

    private void btnUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnUpdateActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = displayTable.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a Record to update the employee details");
            return;
        }
        DefaultTableModel model = (DefaultTableModel) displayTable.getModel();
        EmployeeProfile selectedEntry = (EmployeeProfile) model.getValueAt(selectedRowIndex, 0);
        selectedEntry.setEmployeeId(txtEmployeeId.getText());
        selectedEntry.setName(txtEmployeeName.getText());
        selectedEntry.setAge(Integer.parseInt(txtAge.getText()));
        selectedEntry.setGender(txtGender.getText());
        selectedEntry.setPhone(Long.parseLong(txtPhone.getText()));
        selectedEntry.setEmail(txtEmail.getText());
        selectedEntry.setStartDate(jDateChooseSD.getDate());
        selectedEntry.setLevel(txtLevel.getText());
        selectedEntry.setTeamInfo(txtTeamInfo.getText());
        selectedEntry.setPositionTitle(txtPositionTitle.getText());
        selectedEntry.setPhoto(photo_Path);
  
        populateDataToTable();
        
        //once deleted all the fiels in view model will be deleted
          txtEmployeeId.setText("");
          txtAge.setText("");
          txtEmail.setText("");
          txtEmployeeName.setText("");
          txtGender.setText("");
          txtLevel.setText("");
          txtPhone.setText("");
          txtPositionTitle.setText("");
          jDateChooseSD.setDate(null);
          txtTeamInfo.setText(""); 
          lblDisplayPhoto.setIcon(null);
        


    }//GEN-LAST:event_btnUpdateActionPerformed

    /**
     * Actions while searching through keywords
     * @param evt 
     */
    private void txtSearchKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtSearchKeyReleased
        // TODO add your handling code here:
            DefaultTableModel model = (DefaultTableModel) displayTable.getModel();
            String search = txtSearch.getText().toLowerCase(); // reads the search text as lower case
            TableRowSorter<DefaultTableModel> tr = new TableRowSorter<DefaultTableModel>(model);
            displayTable.setRowSorter(tr);
            tr.setRowFilter(RowFilter.regexFilter(search));
    }//GEN-LAST:event_txtSearchKeyReleased

    private void btnBrowseActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnBrowseActionPerformed
        // TODO add your handling code here:
        JFileChooser browseImageFile = new JFileChooser();
        //Filter image extensions
        FileNameExtensionFilter fnef = new FileNameExtensionFilter("IMAGES", "png", "jpg", "jpeg");
        browseImageFile.addChoosableFileFilter(fnef);
        int showOpenDialogue = browseImageFile.showOpenDialog(null);
         
        if (showOpenDialogue == JFileChooser.APPROVE_OPTION)
        {
            File selectedImageFile = browseImageFile.getSelectedFile();
            String selectedImagePath = selectedImageFile.getAbsolutePath();
            JOptionPane.showMessageDialog(null, selectedImagePath);
            //Display image on jlable
            photo_Path = selectedImagePath;
//            history.setPhoto(selectedImagePath);
            
            ImageIcon ii = new ImageIcon(selectedImagePath);
            //Resize image to fit jlabel
            Image image = ii.getImage().getScaledInstance(lblDisplayPhoto.getWidth(), lblDisplayPhoto.getHeight(), Image.SCALE_SMOOTH);
            lblDisplayPhoto.setIcon(new ImageIcon(image));
        }                
        
        
    }//GEN-LAST:event_btnBrowseActionPerformed


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnBrowse;
    private javax.swing.JButton btnDelete;
    private javax.swing.JButton btnUpdate;
    private javax.swing.JButton btnview;
    private javax.swing.JTable displayTable;
    private com.toedter.calendar.JDateChooser jDateChooseSD;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JLabel lblAge;
    private javax.swing.JLabel lblDisplayPhoto;
    private javax.swing.JLabel lblEmail;
    private javax.swing.JLabel lblEmployeeId;
    private javax.swing.JLabel lblEmployeeName;
    private javax.swing.JLabel lblGender;
    private javax.swing.JLabel lblLevel;
    private javax.swing.JLabel lblPhone;
    private javax.swing.JLabel lblPositionTitle;
    private javax.swing.JLabel lblSearch;
    private javax.swing.JLabel lblStartDate;
    private javax.swing.JLabel lblTeamInfo;
    private javax.swing.JTextField txtAge;
    private javax.swing.JTextField txtEmail;
    private javax.swing.JTextField txtEmployeeId;
    private javax.swing.JTextField txtEmployeeName;
    private javax.swing.JTextField txtGender;
    private javax.swing.JTextField txtLevel;
    private javax.swing.JTextField txtPhone;
    private javax.swing.JTextField txtPositionTitle;
    private javax.swing.JTextField txtSearch;
    private javax.swing.JTextField txtTeamInfo;
    // End of variables declaration//GEN-END:variables

    private void populateDataToTable() {
        //TableModel is used to manipulate table content.
        // type casts tablemodel to defaultTableModel.
    DefaultTableModel model = (DefaultTableModel) displayTable.getModel();
    model.setRowCount(0); // deleting empty records
    
    // looping over profileHistory of employees.
    // getProfileHistory returns the history of employee records.
    for (EmployeeProfile ep : profileHistory.getProfileHistory()){
        
        // row is array of objects with 9 menbers. (1 for each column)
        Object[] row =  new Object[10];
        row[0] = ep/*.getEmployeeId()*/;
        row[1] = ep.getName();
        row[2] = ep.getAge();
        row[3] = ep.getGender();
        row[4] = ep.getPhone();
        row[5] = ep.getEmail();
        row[6] = ep.getStartDate();
        row[7] = ep.getLevel();
        row[8] = ep.getTeamInfo();
        row[9] = ep.getPositionTitle();

        model.addRow(row); // adds row to model

    }
    }
    
}
