/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package com.mycompany.humanresourcemanagement;

/**
 *
 * @author bhargavi
 */
public class JobDetailsJFrame extends javax.swing.JFrame {

    /**
     * Creates new form MainJFrame
     */
    public JobDetailsJFrame() {
        initComponents();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel1 = new javax.swing.JPanel();
        jButton1 = new javax.swing.JButton();
        teamInfoTextField = new javax.swing.JTextField();
        teamInfoLabel = new javax.swing.JLabel();
        startDateLabel = new javax.swing.JLabel();
        levelTextField = new javax.swing.JTextField();
        levelLabel = new javax.swing.JLabel();
        positionTitleTextField = new javax.swing.JTextField();
        positionTitleLabel = new javax.swing.JLabel();
        employeeJobDetailsLabel = new javax.swing.JLabel();
        imageLabel = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);

        jPanel1.setLayout(new org.netbeans.lib.awtextra.AbsoluteLayout());

        jButton1.setText("Submit");
        jPanel1.add(jButton1, new org.netbeans.lib.awtextra.AbsoluteConstraints(230, 290, -1, -1));
        jPanel1.add(teamInfoTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 230, 170, -1));

        teamInfoLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        teamInfoLabel.setForeground(new java.awt.Color(255, 255, 255));
        teamInfoLabel.setText("Team Info :");
        jPanel1.add(teamInfoLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(120, 230, -1, -1));

        startDateLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        startDateLabel.setForeground(new java.awt.Color(255, 255, 255));
        startDateLabel.setText("Start Date :");
        jPanel1.add(startDateLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(130, 190, -1, -1));
        jPanel1.add(levelTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 150, 170, -1));

        levelLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        levelLabel.setForeground(new java.awt.Color(255, 255, 255));
        levelLabel.setText("Level :");
        jPanel1.add(levelLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(160, 150, 70, -1));

        positionTitleTextField.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                positionTitleTextFieldActionPerformed(evt);
            }
        });
        jPanel1.add(positionTitleTextField, new org.netbeans.lib.awtextra.AbsoluteConstraints(260, 100, 170, -1));

        positionTitleLabel.setFont(new java.awt.Font("Times New Roman", 0, 18)); // NOI18N
        positionTitleLabel.setForeground(new java.awt.Color(255, 255, 255));
        positionTitleLabel.setText("Position Title :");
        jPanel1.add(positionTitleLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(100, 100, 140, 30));

        employeeJobDetailsLabel.setFont(new java.awt.Font("Times New Roman", 0, 24)); // NOI18N
        employeeJobDetailsLabel.setForeground(new java.awt.Color(255, 255, 255));
        employeeJobDetailsLabel.setText("Employee Job details");
        jPanel1.add(employeeJobDetailsLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(190, 30, 220, -1));

        imageLabel.setIcon(new javax.swing.ImageIcon("/Users/bhargavi/Downloads/istockphoto-1321467830-612x612.jpeg")); // NOI18N
        jPanel1.add(imageLabel, new org.netbeans.lib.awtextra.AbsoluteConstraints(0, 0, 600, 380));

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 601, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel1, javax.swing.GroupLayout.DEFAULT_SIZE, 381, Short.MAX_VALUE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void positionTitleTextFieldActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_positionTitleTextFieldActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_positionTitleTextFieldActionPerformed

    /**
     * @param args the command line arguments
     */
    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(JobDetailsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(JobDetailsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(JobDetailsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(JobDetailsJFrame.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new JobDetailsJFrame().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JLabel employeeJobDetailsLabel;
    private javax.swing.JLabel imageLabel;
    private javax.swing.JButton jButton1;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JLabel levelLabel;
    private javax.swing.JTextField levelTextField;
    private javax.swing.JLabel positionTitleLabel;
    private javax.swing.JTextField positionTitleTextField;
    private javax.swing.JLabel startDateLabel;
    private javax.swing.JLabel teamInfoLabel;
    private javax.swing.JTextField teamInfoTextField;
    // End of variables declaration//GEN-END:variables
}
