/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import medicalresourcemanagement.Doctor;
import medicalresourcemanagement.DoctorDirectory;
import medicalresourcemanagement.Patient;

/**
 *
 * @author bhargavi
 */
public class AddDoctor extends javax.swing.JPanel {

    public String checkError;
    DoctorDirectory doctorHistory;

    
    public void setDoctorHistory(DoctorDirectory doctorHistory) {
        this.doctorHistory = doctorHistory;
    }
    /**
     * Creates new form AddDoctor
     */
    public AddDoctor() {
        initComponents();
        this.doctorHistory = doctorHistory;

        
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanelManageDoctor = new javax.swing.JPanel();
        spperson = new javax.swing.JScrollPane();
        tblperson = new javax.swing.JTable();
        lbltitle = new javax.swing.JLabel();
        lblcommunity2 = new javax.swing.JLabel();
        lblhouseaddress2 = new javax.swing.JLabel();
        lblcity2 = new javax.swing.JLabel();
        lblusername2 = new javax.swing.JLabel();
        lblpassword2 = new javax.swing.JLabel();
        txthouseaddress2 = new javax.swing.JTextField();
        txtusername2 = new javax.swing.JTextField();
        txtpassword2 = new javax.swing.JTextField();
        cbcommunity2 = new javax.swing.JComboBox<>();
        btnupdate = new javax.swing.JButton();
        btnViewAndUpdate = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();
        cbCity = new javax.swing.JComboBox<>();
        jPanelAddDoctor = new javax.swing.JPanel();
        lblcommunity1 = new javax.swing.JLabel();
        lblhouseaddress1 = new javax.swing.JLabel();
        lblcity1 = new javax.swing.JLabel();
        lblusername1 = new javax.swing.JLabel();
        lblpassword1 = new javax.swing.JLabel();
        txthouseaddress1 = new javax.swing.JTextField();
        txtusername1 = new javax.swing.JTextField();
        txtpassword1 = new javax.swing.JTextField();
        cbcommunity1 = new javax.swing.JComboBox<>();
        btnadd1 = new javax.swing.JButton();
        lblAddTitle1 = new javax.swing.JLabel();
        lblErrorHouseAddress1 = new javax.swing.JLabel();
        lblErrorUserName1 = new javax.swing.JLabel();
        lblErrorPassword1 = new javax.swing.JLabel();
        cbCity1 = new javax.swing.JComboBox<>();

        setPreferredSize(new java.awt.Dimension(900, 700));

        jTabbedPane1.setPreferredSize(new java.awt.Dimension(900, 700));

        jPanelManageDoctor.setPreferredSize(new java.awt.Dimension(900, 700));

        spperson.setPreferredSize(new java.awt.Dimension(900, 100));

        tblperson.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null},
                {null, null, null, null, null, null}
            },
            new String [] {
                "Doctor Id", "Community", "House Address", "City", "Username", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, true, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblperson.setPreferredSize(new java.awt.Dimension(900, 80));
        spperson.setViewportView(tblperson);

        lbltitle.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
        lbltitle.setText("Manage Doctor");

        lblcommunity2.setText("Community :");

        lblhouseaddress2.setText("Hospital Name:");

        lblcity2.setText("City :");

        lblusername2.setText("User Name :");

        lblpassword2.setText("Password :");

        cbcommunity2.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Community", "Brigham", "Huntington Avenue", "Mission Hill", "Brookline", "Fenway" }));

        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        btnViewAndUpdate.setText("View & Update");
        btnViewAndUpdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnViewAndUpdateActionPerformed(evt);
            }
        });

        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        jLabel1.setText("Search by Id");

        jLabel2.setText("Search by Name");

        cbCity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));

        javax.swing.GroupLayout jPanelManageDoctorLayout = new javax.swing.GroupLayout(jPanelManageDoctor);
        jPanelManageDoctor.setLayout(jPanelManageDoctorLayout);
        jPanelManageDoctorLayout.setHorizontalGroup(
            jPanelManageDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelManageDoctorLayout.createSequentialGroup()
                .addGroup(jPanelManageDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelManageDoctorLayout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(spperson, javax.swing.GroupLayout.PREFERRED_SIZE, 989, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelManageDoctorLayout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(btnupdate))
                    .addGroup(jPanelManageDoctorLayout.createSequentialGroup()
                        .addGap(416, 416, 416)
                        .addComponent(lbltitle))
                    .addGroup(jPanelManageDoctorLayout.createSequentialGroup()
                        .addGroup(jPanelManageDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelManageDoctorLayout.createSequentialGroup()
                                .addGap(217, 217, 217)
                                .addComponent(lblusername2))
                            .addGroup(jPanelManageDoctorLayout.createSequentialGroup()
                                .addGap(224, 224, 224)
                                .addComponent(lblpassword2)))
                        .addGap(132, 132, 132)
                        .addGroup(jPanelManageDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(txtpassword2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(txtusername2, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelManageDoctorLayout.createSequentialGroup()
                                .addGap(390, 390, 390)
                                .addComponent(btnViewAndUpdate)
                                .addGap(18, 18, 18)
                                .addComponent(btndelete))))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelManageDoctorLayout.createSequentialGroup()
                        .addGroup(jPanelManageDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanelManageDoctorLayout.createSequentialGroup()
                                .addGap(24, 24, 24)
                                .addComponent(lblcommunity2))
                            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelManageDoctorLayout.createSequentialGroup()
                                .addContainerGap()
                                .addGroup(jPanelManageDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblcity2, javax.swing.GroupLayout.Alignment.TRAILING)
                                    .addComponent(lblhouseaddress2, javax.swing.GroupLayout.Alignment.TRAILING))))
                        .addGap(132, 132, 132)
                        .addGroup(jPanelManageDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addComponent(cbCity, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addGroup(jPanelManageDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                                .addComponent(txthouseaddress2, javax.swing.GroupLayout.DEFAULT_SIZE, 196, Short.MAX_VALUE)
                                .addComponent(cbcommunity2, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                        .addGap(401, 401, 401)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelManageDoctorLayout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
        );
        jPanelManageDoctorLayout.setVerticalGroup(
            jPanelManageDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelManageDoctorLayout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbltitle)
                .addGap(63, 63, 63)
                .addGroup(jPanelManageDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(spperson, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(jPanelManageDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(btnViewAndUpdate)
                    .addComponent(btndelete))
                .addGap(77, 77, 77)
                .addGroup(jPanelManageDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblcity2)
                    .addComponent(cbCity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addGroup(jPanelManageDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblcommunity2)
                    .addComponent(cbcommunity2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanelManageDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblhouseaddress2)
                    .addComponent(txthouseaddress2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addGroup(jPanelManageDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblusername2)
                    .addComponent(txtusername2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanelManageDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpassword2)
                    .addComponent(txtpassword2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnupdate))
        );

        jTabbedPane1.addTab("Manage Doctor", jPanelManageDoctor);

        jPanelAddDoctor.setPreferredSize(new java.awt.Dimension(900, 700));

        lblcommunity1.setText("Community :");

        lblhouseaddress1.setText("House Address :");

        lblcity1.setText("City :");

        lblusername1.setText("User Name :");

        lblpassword1.setText("Password :");

        txtpassword1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpassword1KeyReleased(evt);
            }
        });

        cbcommunity1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Brigham", "Huntington Avenue", "Mission Hill", "Brookline", "Fenway" }));
        cbcommunity1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcommunity1ActionPerformed(evt);
            }
        });

        btnadd1.setText("Add");
        btnadd1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnadd1ActionPerformed(evt);
            }
        });

        lblAddTitle1.setFont(new java.awt.Font("Helvetica Neue", 1, 18)); // NOI18N
        lblAddTitle1.setHorizontalAlignment(javax.swing.SwingConstants.CENTER);
        lblAddTitle1.setText("Add Doctor");
        lblAddTitle1.setHorizontalTextPosition(javax.swing.SwingConstants.CENTER);

        lblErrorHouseAddress1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblErrorHouseAddress1KeyReleased(evt);
            }
        });

        lblErrorUserName1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblErrorUserName1KeyReleased(evt);
            }
        });

        lblErrorPassword1.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblErrorPassword1KeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanelAddDoctorLayout = new javax.swing.GroupLayout(jPanelAddDoctor);
        jPanelAddDoctor.setLayout(jPanelAddDoctorLayout);
        jPanelAddDoctorLayout.setHorizontalGroup(
            jPanelAddDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddDoctorLayout.createSequentialGroup()
                .addGap(337, 337, 337)
                .addComponent(lblAddTitle1, javax.swing.GroupLayout.PREFERRED_SIZE, 249, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanelAddDoctorLayout.createSequentialGroup()
                .addGroup(jPanelAddDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAddDoctorLayout.createSequentialGroup()
                        .addGap(178, 178, 178)
                        .addGroup(jPanelAddDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                            .addComponent(lblpassword1)
                            .addComponent(lblcity1)
                            .addComponent(lblhouseaddress1)
                            .addComponent(lblcommunity1))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 164, Short.MAX_VALUE)
                        .addGroup(jPanelAddDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                            .addComponent(cbcommunity1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                            .addComponent(txthouseaddress1, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                            .addComponent(txtpassword1, javax.swing.GroupLayout.DEFAULT_SIZE, 220, Short.MAX_VALUE)
                            .addComponent(cbCity1, 0, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)))
                    .addGroup(jPanelAddDoctorLayout.createSequentialGroup()
                        .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(txtusername1, javax.swing.GroupLayout.PREFERRED_SIZE, 220, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(84, 84, 84)
                .addGroup(jPanelAddDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErrorPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorUserName1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorHouseAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(173, 173, 173))
            .addGroup(jPanelAddDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelAddDoctorLayout.createSequentialGroup()
                    .addGroup(jPanelAddDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanelAddDoctorLayout.createSequentialGroup()
                            .addGap(206, 206, 206)
                            .addComponent(lblusername1))
                        .addGroup(jPanelAddDoctorLayout.createSequentialGroup()
                            .addGap(337, 337, 337)
                            .addComponent(btnadd1)))
                    .addGap(616, 616, 616)))
        );

        jPanelAddDoctorLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {cbcommunity1, txthouseaddress1, txtpassword1, txtusername1});

        jPanelAddDoctorLayout.setVerticalGroup(
            jPanelAddDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanelAddDoctorLayout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lblAddTitle1)
                .addGap(169, 169, 169)
                .addGroup(jPanelAddDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(lblcity1)
                    .addComponent(cbCity1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanelAddDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanelAddDoctorLayout.createSequentialGroup()
                        .addGap(52, 52, 52)
                        .addComponent(lblErrorHouseAddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanelAddDoctorLayout.createSequentialGroup()
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                        .addGroup(jPanelAddDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(cbcommunity1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addComponent(lblcommunity1))
                        .addGap(18, 18, 18)
                        .addGroup(jPanelAddDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                            .addComponent(lblhouseaddress1)
                            .addComponent(txthouseaddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanelAddDoctorLayout.createSequentialGroup()
                        .addGap(89, 89, 89)
                        .addComponent(txtusername1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)))
                .addGap(18, 18, 18)
                .addComponent(lblErrorUserName1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(1, 1, 1)
                .addGroup(jPanelAddDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblpassword1)
                    .addComponent(txtpassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorPassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(195, Short.MAX_VALUE))
            .addGroup(jPanelAddDoctorLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanelAddDoctorLayout.createSequentialGroup()
                    .addGap(375, 375, 375)
                    .addComponent(lblusername1)
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 64, Short.MAX_VALUE)
                    .addComponent(btnadd1)
                    .addGap(184, 184, 184)))
        );

        jTabbedPane1.addTab("Add Doctor", jPanelAddDoctor);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 1025, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, layout.createSequentialGroup()
                .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addContainerGap())
        );
    }// </editor-fold>//GEN-END:initComponents

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
        int selectedRowIndex = tblperson.getSelectedRow();  // gives index of selected rows
        if(selectedRowIndex < 0)
        {
            JOptionPane.showMessageDialog(this, "Select a entry to delete");
            return;
        }

        DefaultTableModel model = (DefaultTableModel)tblperson.getModel();
        Doctor selectedEntry = doctorHistory.getDoctorHistory().get(selectedRowIndex);
        doctorHistory.deleteDoctor(selectedEntry);

        JOptionPane.showMessageDialog(this, "Selected Employee Deleted");
        populateDataToTable(); //  deletes record from table and updates all entries
    }//GEN-LAST:event_btndeleteActionPerformed

    private void btnViewAndUpdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnViewAndUpdateActionPerformed
        // TODO add your handling code here:

        int selectedRowIndex = tblperson.getSelectedRow();  // gives index of selected rows
        if(selectedRowIndex < 0)
        {
            JOptionPane.showMessageDialog(this, "Select a entry to view");
            return;
        }

        txthouseaddress1.setText(doctorHistory.getDoctorHistory().get(selectedRowIndex).getHouse());
        cbcommunity1.setSelectedItem(doctorHistory.getDoctorHistory().get(selectedRowIndex).getCommunityName());
        cbCity.setText(doctorHistory.getDoctorHistory().get(selectedRowIndex).getCityName());
        txtusername1.setText(doctorHistory.getDoctorHistory().get(selectedRowIndex).getUserName());
        txtpassword1.setText(doctorHistory.getDoctorHistory().get(selectedRowIndex).getPassword());
    }//GEN-LAST:event_btnViewAndUpdateActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:

        int selectedRowIndex = tblperson.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a Record to update the employee details");
            return;
        }

        DefaultTableModel model = (DefaultTableModel) tblperson.getModel();
        Doctor selectedEntry = doctorHistory.getDoctorHistory().get(selectedRowIndex);

        //Patient selectedEntry = (Patient) model.getValueAt(selectedRowIndex, 1);
        //        selectedEntry.setEmployeeId(txtEmployeeId.getText());
        
        selectedEntry.setHouseAddress(txthouseaddress1.getText());
        selectedEntry.setCity(txtcity1.getText());
        selectedEntry.setUserName(txtusername1.getText());
        selectedEntry.setPassword(txtpassword1.getText());

        populateDataToTable();

        //once deleted all the fiels in view model will be deleted
        
        txthouseaddress1.setText("");
        txtcity1.setText("");
        cbcommunity1.setSelectedItem(-1);
        txtusername1.setText("");
        txtpassword1.setText("");
    }//GEN-LAST:event_btnupdateActionPerformed

    private void lblErrorPassword1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblErrorPassword1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lblErrorPassword1KeyReleased

    private void lblErrorUserName1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblErrorUserName1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lblErrorUserName1KeyReleased

    private void lblErrorHouseAddress1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblErrorHouseAddress1KeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lblErrorHouseAddress1KeyReleased

    private void btnadd1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnadd1ActionPerformed
        // TODO add your handling code here:
        if(checkError != null /*|| (txtname.getText() == null  || txtphone.getText() == null || txthouseaddress.getText() == null || txtcity.getText() ==null || txtusername.getText() == null ||txtpassword.getText() == null)*/){
            JOptionPane.showMessageDialog(this,"Please provide valid inputs to all fields");

        }
        else{
            
            String community = cbcommunity1.getSelectedItem().toString();
            String homeAddress = txthouseaddress1.getText();
            String city = cbCity1.getSelectedItem().toString();
            String userName = txtusername1.getText();
            String password = txtpassword1.getText();

            Doctor doc = doctorHistory.addNewDoctor(); //

            // sets value to ArrayList from the fields that the data is entered.

            
            doc.setCommunityName(community);
            doc.setHouse(homeAddress);
            doc.setCity(city);
            doc.setUserName(userName);
            doc.setPassword(password);

            // shows a dialogue message when the data clicked save button
            JOptionPane.showMessageDialog(this,"Employee details added");

            // empties all the fields after saving the entered data to ArrayList to facilitate new entries.
          
            cbcommunity1.setSelectedIndex(-1);
            txthouseaddress1.setText("");
            cbCity1.setSelectedIndex(-1);
            txtusername1.setText("");
            txtpassword1.setText("");
            populateDataToTable();

        }
    }//GEN-LAST:event_btnadd1ActionPerformed

    private void cbcommunity1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcommunity1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbcommunity1ActionPerformed

    private void txtpassword1KeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpassword1KeyReleased
        // TODO add your handling code here:
        String PATTERN = "^(?=.*[0-9])"
        + "(?=.*[a-z])(?=.*[A-Z])"
        + "(?=.*[@#$%^&+=])"
        + "(?=\\S+$).{8,20}$"; // regex that matches the input
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(txtpassword1.getText()); // gets text from field and matched against the regex

        if(!match.matches())
        {
            checkError = "error";
            lblErrorPassword1.setText("Make sure the password has atleast one number , a capital letter and a special character"); //throws message if input other than text is entered
        }
        else
        {
            checkError = null;
            lblErrorPassword1.setText(null);
        }
    }//GEN-LAST:event_txtpassword1KeyReleased


    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnViewAndUpdate;
    private javax.swing.JButton btnadd1;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox<String> cbCity;
    private javax.swing.JComboBox<String> cbCity1;
    private javax.swing.JComboBox<String> cbcommunity1;
    private javax.swing.JComboBox<String> cbcommunity2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanelAddDoctor;
    private javax.swing.JPanel jPanelManageDoctor;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblAddTitle1;
    private javax.swing.JLabel lblErrorHouseAddress1;
    private javax.swing.JLabel lblErrorPassword1;
    private javax.swing.JLabel lblErrorUserName1;
    private javax.swing.JLabel lblcity1;
    private javax.swing.JLabel lblcity2;
    private javax.swing.JLabel lblcommunity1;
    private javax.swing.JLabel lblcommunity2;
    private javax.swing.JLabel lblhouseaddress1;
    private javax.swing.JLabel lblhouseaddress2;
    private javax.swing.JLabel lblpassword1;
    private javax.swing.JLabel lblpassword2;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JLabel lblusername1;
    private javax.swing.JLabel lblusername2;
    private javax.swing.JScrollPane spperson;
    private javax.swing.JTable tblperson;
    private javax.swing.JTextField txthouseaddress1;
    private javax.swing.JTextField txthouseaddress2;
    private javax.swing.JTextField txtpassword1;
    private javax.swing.JTextField txtpassword2;
    private javax.swing.JTextField txtusername1;
    private javax.swing.JTextField txtusername2;
    // End of variables declaration//GEN-END:variables


    
    private void populateDataToTable() {
        //TableModel is used to manipulate table content.
        // type casts tablemodel to defaultTableModel.
    DefaultTableModel model = (DefaultTableModel) tblperson.getModel();
    model.setRowCount(0); // deleting empty records
    
    // looping over profileHistory of employees.
    // getProfileHistory returns the history of employee records.
    for (Doctor d : doctorHistory.getDoctorHistory()){
        
        // row is array of objects with 9 menbers. (1 for each column)
        Object[] row =  new Object[10];
        row[0] = d.getDoctorId()/*.getPatientId()*/;/*.getEmployeeId()*/
        row[1] = d.getName();
        row[2] = d.getAge();
        row[3] = d.getPhone();
        row[4] = d.getCommunityName();
        row[5] = d.getHouse();
        row[6] = d.getCity();
        row[7] = d.getUserName();
        row[8] = d.getPassword();
                
        

        model.addRow(row); // adds row to model

    }
    }
}
