/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JPanel.java to edit this template
 */
package ui;

import java.util.regex.Matcher;
import java.util.regex.Pattern;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;
import medicalresourcemanagement.Patient;
import medicalresourcemanagement.Person;
import medicalresourcemanagement.PatientDirectory;

/**
 *
 * @author bhargavi
 */
public class AddPatient extends javax.swing.JPanel {

        PatientDirectory patientHistory;
        public String checkError;

   

    public void setPatientHistory(PatientDirectory patientHistory) {
        this.patientHistory = patientHistory;
    }
    /**
     * Creates new form temp
     */
    public AddPatient(PatientDirectory patientHistory) {
        initComponents();
        this.patientHistory = patientHistory;
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jTabbedPane1 = new javax.swing.JTabbedPane();
        jPanel1 = new javax.swing.JPanel();
        lblname = new javax.swing.JLabel();
        lblage = new javax.swing.JLabel();
        lblphone = new javax.swing.JLabel();
        lblcommunity = new javax.swing.JLabel();
        lblhouseaddress = new javax.swing.JLabel();
        lblcity = new javax.swing.JLabel();
        lblusername = new javax.swing.JLabel();
        lblpassword = new javax.swing.JLabel();
        txtage = new javax.swing.JTextField();
        txtname = new javax.swing.JTextField();
        txtphone = new javax.swing.JTextField();
        txthouseaddress = new javax.swing.JTextField();
        txtcity = new javax.swing.JTextField();
        txtusername = new javax.swing.JTextField();
        txtpassword = new javax.swing.JTextField();
        cbcommunity = new javax.swing.JComboBox<>();
        btnadd = new javax.swing.JButton();
        lblAddTitle = new javax.swing.JLabel();
        lblErrorName = new javax.swing.JLabel();
        lblErrorAge = new javax.swing.JLabel();
        lblErrorPhone = new javax.swing.JLabel();
        lblErrorHouseAddress = new javax.swing.JLabel();
        lblErrorCity = new javax.swing.JLabel();
        lblErrorUserName = new javax.swing.JLabel();
        lblErrorPassword = new javax.swing.JLabel();
        jPanel2 = new javax.swing.JPanel();
        spperson = new javax.swing.JScrollPane();
        tblperson = new javax.swing.JTable();
        lblname1 = new javax.swing.JLabel();
        lbltitle = new javax.swing.JLabel();
        lblage1 = new javax.swing.JLabel();
        lblphone1 = new javax.swing.JLabel();
        lblcommunity1 = new javax.swing.JLabel();
        lblhouseaddress1 = new javax.swing.JLabel();
        lblcity1 = new javax.swing.JLabel();
        lblusername1 = new javax.swing.JLabel();
        lblpassword1 = new javax.swing.JLabel();
        txtage1 = new javax.swing.JTextField();
        txtname1 = new javax.swing.JTextField();
        txtphone1 = new javax.swing.JTextField();
        txthouseaddress1 = new javax.swing.JTextField();
        txtcity1 = new javax.swing.JTextField();
        txtusername1 = new javax.swing.JTextField();
        txtpassword1 = new javax.swing.JTextField();
        cbcommunity1 = new javax.swing.JComboBox<>();
        btnupdate = new javax.swing.JButton();
        jButton1 = new javax.swing.JButton();
        btndelete = new javax.swing.JButton();
        jTextField1 = new javax.swing.JTextField();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        jTextField2 = new javax.swing.JTextField();

        setPreferredSize(new java.awt.Dimension(900, 700));

        jTabbedPane1.setSize(new java.awt.Dimension(900, 700));
        jTabbedPane1.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jTabbedPane1MouseClicked(evt);
            }
        });

        jPanel1.setPreferredSize(new java.awt.Dimension(900, 700));

        lblname.setText("Name :");

        lblage.setText("Age :");

        lblphone.setText("Phone :");

        lblcommunity.setText("Community :");

        lblhouseaddress.setText("House Address :");

        lblcity.setText("City :");

        lblusername.setText("User Name :");

        lblpassword.setText("Password :");

        txtage.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtageActionPerformed(evt);
            }
        });
        txtage.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtageKeyReleased(evt);
            }
        });

        txtname.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtnameActionPerformed(evt);
            }
        });
        txtname.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtnameKeyReleased(evt);
            }
        });

        txtphone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtphoneKeyReleased(evt);
            }
        });

        txtcity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtcityKeyReleased(evt);
            }
        });

        txtpassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                txtpasswordKeyReleased(evt);
            }
        });

        cbcommunity.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Brigham", "Huntington Avenue", "Mission Hill", "Brookline", "Fenway" }));
        cbcommunity.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbcommunityActionPerformed(evt);
            }
        });

        btnadd.setText("Add");
        btnadd.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnaddActionPerformed(evt);
            }
        });

        lblAddTitle.setText("Add Patient");

        lblErrorName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblErrorNameKeyReleased(evt);
            }
        });

        lblErrorAge.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblErrorAgeKeyReleased(evt);
            }
        });

        lblErrorPhone.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblErrorPhoneKeyReleased(evt);
            }
        });

        lblErrorHouseAddress.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblErrorHouseAddressKeyReleased(evt);
            }
        });

        lblErrorCity.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblErrorCityKeyReleased(evt);
            }
        });

        lblErrorUserName.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblErrorUserNameKeyReleased(evt);
            }
        });

        lblErrorPassword.addKeyListener(new java.awt.event.KeyAdapter() {
            public void keyReleased(java.awt.event.KeyEvent evt) {
                lblErrorPasswordKeyReleased(evt);
            }
        });

        javax.swing.GroupLayout jPanel1Layout = new javax.swing.GroupLayout(jPanel1);
        jPanel1.setLayout(jPanel1Layout);
        jPanel1Layout.setHorizontalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(337, 337, 337)
                .addComponent(lblAddTitle)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel1Layout.createSequentialGroup()
                .addGap(232, 232, 232)
                .addComponent(lblname)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 404, Short.MAX_VALUE)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addComponent(lblErrorPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorCity, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorHouseAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorAge, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(lblErrorName, javax.swing.GroupLayout.PREFERRED_SIZE, 173, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(173, 173, 173))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(181, 181, 181)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                    .addComponent(lblphone)
                                    .addGroup(jPanel1Layout.createSequentialGroup()
                                        .addGap(12, 12, 12)
                                        .addComponent(lblage)))
                                .addComponent(lblcommunity)
                                .addComponent(lblcity)
                                .addComponent(lblhouseaddress)
                                .addComponent(lblusername)
                                .addComponent(lblpassword))
                            .addGap(144, 144, 144)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                                .addComponent(txtname, javax.swing.GroupLayout.DEFAULT_SIZE, 219, Short.MAX_VALUE)
                                .addComponent(txtage)
                                .addComponent(txtphone)
                                .addGroup(jPanel1Layout.createSequentialGroup()
                                    .addComponent(cbcommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                                    .addGap(0, 0, Short.MAX_VALUE))
                                .addComponent(txthouseaddress)
                                .addComponent(txtcity)
                                .addComponent(txtusername)
                                .addComponent(txtpassword)))
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addGap(156, 156, 156)
                            .addComponent(btnadd)))
                    .addGap(382, 382, 382)))
        );
        jPanel1Layout.setVerticalGroup(
            jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel1Layout.createSequentialGroup()
                .addGap(59, 59, 59)
                .addComponent(lblAddTitle)
                .addGap(111, 111, 111)
                .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(lblname)
                    .addComponent(lblErrorName, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(18, 18, 18)
                .addComponent(lblErrorAge, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                .addComponent(lblErrorPhone, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(52, 52, 52)
                .addComponent(lblErrorHouseAddress, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblErrorCity, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(lblErrorUserName, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(lblErrorPassword, javax.swing.GroupLayout.PREFERRED_SIZE, 17, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(239, Short.MAX_VALUE))
            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                .addGroup(jPanel1Layout.createSequentialGroup()
                    .addGap(183, 183, 183)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                        .addComponent(txtphone, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGroup(jPanel1Layout.createSequentialGroup()
                            .addComponent(txtname, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                            .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(lblage)
                                .addComponent(txtage, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                            .addComponent(lblphone)))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblcommunity)
                        .addComponent(cbcommunity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblhouseaddress)
                        .addComponent(txthouseaddress, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblcity)
                        .addComponent(txtcity, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblusername)
                        .addComponent(txtusername, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED)
                    .addGroup(jPanel1Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                        .addComponent(lblpassword)
                        .addComponent(txtpassword, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 35, Short.MAX_VALUE)
                    .addComponent(btnadd)
                    .addGap(184, 184, 184)))
        );

        jTabbedPane1.addTab("Add Patient", jPanel1);

        jPanel2.setPreferredSize(new java.awt.Dimension(900, 700));

        spperson.setPreferredSize(new java.awt.Dimension(900, 100));

        tblperson.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null},
                {null, null, null, null, null, null, null, null, null}
            },
            new String [] {
                "Employee Id", "Name", "Age", "Phone", "Community", "House Address", "City", "Username", "Password"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.String.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class, java.lang.Object.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, true, false, false, false, true
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tblperson.setPreferredSize(new java.awt.Dimension(900, 80));
        spperson.setViewportView(tblperson);

        lblname1.setText("Name :");

        lbltitle.setFont(new java.awt.Font("Helvetica Neue", 3, 18)); // NOI18N
        lbltitle.setText("Manage Patient");

        lblage1.setText("Age :");

        lblphone1.setText("Phone :");

        lblcommunity1.setText("Community :");

        lblhouseaddress1.setText("House Address :");

        lblcity1.setText("City :");

        lblusername1.setText("User Name :");

        lblpassword1.setText("Password :");

        txtage1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                txtage1ActionPerformed(evt);
            }
        });

        cbcommunity1.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Select Community", "Brigham", "Huntington Avenue", "Mission Hill", "Brookline", "Fenway" }));

        btnupdate.setText("Update");
        btnupdate.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnupdateActionPerformed(evt);
            }
        });

        jButton1.setText("View & Update");
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });

        btndelete.setText("Delete");
        btndelete.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btndeleteActionPerformed(evt);
            }
        });

        jLabel1.setText("Search by Id");

        jLabel2.setText("Search by Name");

        javax.swing.GroupLayout jPanel2Layout = new javax.swing.GroupLayout(jPanel2);
        jPanel2.setLayout(jPanel2Layout);
        jPanel2Layout.setHorizontalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(spperson, javax.swing.GroupLayout.PREFERRED_SIZE, 989, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(lblname1)
                        .addGap(146, 146, 146)
                        .addComponent(txtname1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(134, 134, 134)
                        .addComponent(jButton1)
                        .addGap(18, 18, 18)
                        .addComponent(btndelete))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(258, 258, 258)
                        .addComponent(lblage1)
                        .addGap(146, 146, 146)
                        .addComponent(txtage1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(246, 246, 246)
                        .addComponent(lblphone1)
                        .addGap(144, 144, 144)
                        .addComponent(txtphone1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(216, 216, 216)
                        .addComponent(lblcommunity1)
                        .addGap(144, 144, 144)
                        .addComponent(cbcommunity1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(192, 192, 192)
                        .addComponent(lblhouseaddress1)
                        .addGap(144, 144, 144)
                        .addComponent(txthouseaddress1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(259, 259, 259)
                        .addComponent(lblcity1)
                        .addGap(144, 144, 144)
                        .addComponent(txtcity1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(217, 217, 217)
                        .addComponent(lblusername1)
                        .addGap(144, 144, 144)
                        .addComponent(txtusername1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(224, 224, 224)
                        .addComponent(lblpassword1)
                        .addGap(144, 144, 144)
                        .addComponent(txtpassword1, javax.swing.GroupLayout.PREFERRED_SIZE, 196, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(348, 348, 348)
                        .addComponent(btnupdate))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(416, 416, 416)
                        .addComponent(lbltitle)))
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(21, 21, 21)
                .addComponent(jLabel1, javax.swing.GroupLayout.PREFERRED_SIZE, 99, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(jLabel2)
                .addGap(26, 26, 26)
                .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, 98, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(134, 134, 134))
        );
        jPanel2Layout.setVerticalGroup(
            jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel2Layout.createSequentialGroup()
                .addGap(26, 26, 26)
                .addComponent(lbltitle)
                .addGap(63, 63, 63)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                    .addComponent(jLabel1)
                    .addComponent(jTextField1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(jLabel2)
                    .addComponent(jTextField2, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(25, 25, 25)
                .addComponent(spperson, javax.swing.GroupLayout.PREFERRED_SIZE, 100, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(14, 14, 14)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(19, 19, 19)
                        .addComponent(lblname1))
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(16, 16, 16)
                        .addComponent(txtname1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                    .addComponent(jButton1)
                    .addComponent(btndelete))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblage1))
                    .addComponent(txtage1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(6, 6, 6)
                        .addComponent(lblphone1))
                    .addComponent(txtphone1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblcommunity1))
                    .addComponent(cbcommunity1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblhouseaddress1))
                    .addComponent(txthouseaddress1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(12, 12, 12)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblcity1))
                    .addComponent(txtcity1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblusername1))
                    .addComponent(txtusername1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(6, 6, 6)
                .addGroup(jPanel2Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel2Layout.createSequentialGroup()
                        .addGap(3, 3, 3)
                        .addComponent(lblpassword1))
                    .addComponent(txtpassword1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addGap(35, 35, 35)
                .addComponent(btnupdate))
        );

        jTabbedPane1.addTab("Manage Patient", jPanel2);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(this);
        this.setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 1024, Short.MAX_VALUE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jTabbedPane1, javax.swing.GroupLayout.DEFAULT_SIZE, 700, Short.MAX_VALUE)
        );
    }// </editor-fold>//GEN-END:initComponents

    private void txtageActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtageActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtageActionPerformed

    private void btnaddActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnaddActionPerformed
        // TODO add your handling code here:
        if(checkError != null /*|| (txtname.getText() == null  || txtphone.getText() == null || txthouseaddress.getText() == null || txtcity.getText() ==null || txtusername.getText() == null ||txtpassword.getText() == null)*/){
            JOptionPane.showMessageDialog(this,"Please provide valid inputs to all fields");

        }
        else{
            String name = txtname.getText();
            int age = Integer.parseInt(txtage.getText());
            long phone = Long.parseLong(txtphone.getText());
            String community = cbcommunity.getSelectedItem().toString();
            String homeAddress = txthouseaddress.getText();
            String city = txtcity.getText();
            String userName = txtusername.getText();
            String password = txtpassword.getText();

            Patient per = patientHistory.addNewPatient(); // 

            // sets value to ArrayList from the fields that the data is entered.

            per.setName(name);
            per.setAge(age);
            per.setPhone(phone);
            per.setCommunityName(community);
            per.setHouse(homeAddress);
            per.setCity(city);
            per.setUserName(userName);
            per.setPassword(password);

            // shows a dialogue message when the data clicked save button
            JOptionPane.showMessageDialog(this,"Employee details added");

            // empties all the fields after saving the entered data to ArrayList to facilitate new entries.
            txtname.setText("");
            txtage.setText("");
            txtphone.setText("");
            cbcommunity.setSelectedIndex(-1);
            txthouseaddress.setText("");
            txtcity.setText("");
            txtusername.setText("");
            txtpassword.setText("");
            populateDataToTable();

        }

    }//GEN-LAST:event_btnaddActionPerformed

    private void txtage1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtage1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtage1ActionPerformed

    private void btnupdateActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnupdateActionPerformed
        // TODO add your handling code here:

         int selectedRowIndex = tblperson.getSelectedRow();
        if (selectedRowIndex < 0) {
            JOptionPane.showMessageDialog(this, "Please select a Record to update the employee details");
            return;
        }
        
        DefaultTableModel model = (DefaultTableModel) tblperson.getModel();
        Patient selectedEntry = patientHistory.getPatientHistory().get(selectedRowIndex);

        //Patient selectedEntry = (Patient) model.getValueAt(selectedRowIndex, 1);
//        selectedEntry.setEmployeeId(txtEmployeeId.getText());
        selectedEntry.setName(txtname1.getText());
        
        selectedEntry.setAge(Integer.parseInt(txtage1.getText()));
        selectedEntry.setPhone(Long.parseLong(txtphone1.getText()));
        selectedEntry.setHouse(txthouseaddress1.getText());
        selectedEntry.setCity(txtcity1.getText());
        selectedEntry.setUserName(txtusername1.getText());
        selectedEntry.setPassword(txtpassword1.getText());
        
        

  
        populateDataToTable();
        
        //once deleted all the fiels in view model will be deleted
          txtname1.setText("");
          txtage1.setText("");          
          txtphone1.setText("");
          txthouseaddress1.setText("");
          txtcity1.setText("");
          cbcommunity.setSelectedItem(-1);
          txtusername1.setText(""); 
          txtpassword1.setText(""); 

    }//GEN-LAST:event_btnupdateActionPerformed

    private void lblErrorNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblErrorNameKeyReleased
        // TODO add your handling code here:
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lblErrorNameKeyReleased

    private void lblErrorAgeKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblErrorAgeKeyReleased
        // TODO add your handling code here:
        
    }//GEN-LAST:event_lblErrorAgeKeyReleased

    private void lblErrorPhoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblErrorPhoneKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9 +()-]{10}$";  // pattern to check against input
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(txtphone.getText());
        if(!match.matches())
        {
            checkError = "error";
            lblErrorPhone.setText("Please Enter a 10 digit number."); // throws error message
        }
        else
        {
            checkError = null;
            lblErrorPhone.setText(null);
        }
    }//GEN-LAST:event_lblErrorPhoneKeyReleased

    private void lblErrorHouseAddressKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblErrorHouseAddressKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lblErrorHouseAddressKeyReleased

    private void lblErrorCityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblErrorCityKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lblErrorCityKeyReleased

    private void lblErrorUserNameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblErrorUserNameKeyReleased
        // TODO add your handling code here:
    }//GEN-LAST:event_lblErrorUserNameKeyReleased

    private void lblErrorPasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_lblErrorPasswordKeyReleased
        // TODO add your handling code here:
        
      
    }//GEN-LAST:event_lblErrorPasswordKeyReleased

    private void txtnameKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtnameKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z '/:]+$"; // regex that matches the input
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(txtname.getText()); // gets text from field and matched against the regex
     
        if(!match.matches())
        {
            checkError = "error";
            lblErrorName.setText("Enter a valid Input."); //throws message if input other than text is entered
        }
        else
        {
            checkError = null;
            lblErrorName.setText(null);
        }
    }//GEN-LAST:event_txtnameKeyReleased

    private void txtageKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtageKeyReleased
        // TODO add your handling code here:
         String PATTERN = "^[0-9 +()-]{1,3}$";  // pattern to check against input
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(txtage.getText());
        if(!match.matches())
        {
            checkError = "error";
            lblErrorAge.setText("Enter Valid Age"); // throws error message
        }
        else
        {
            checkError = null;
            lblErrorAge.setText(null);
        }
    }//GEN-LAST:event_txtageKeyReleased

    private void txtphoneKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtphoneKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[0-9 +()-]{10}$";  // pattern to check against input
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(txtphone.getText());
        if(!match.matches())
        {
            checkError = "error";
            lblErrorPhone.setText("Please Enter a 10 digit number."); // throws error message
        }
        else
        {
            checkError = null;
            lblErrorPhone.setText(null);
        }
    }//GEN-LAST:event_txtphoneKeyReleased

    private void txtcityKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtcityKeyReleased
        // TODO add your handling code here:
        String PATTERN = "^[a-zA-Z '/:]+$"; // regex that matches the input
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(txtcity.getText()); // gets text from field and matched against the regex
     
        if(!match.matches())
        {
            checkError = "error";
            lblErrorCity.setText("Enter a valid City name."); //throws message if input other than text is entered
        }
        else
        {
            checkError = null;
            lblErrorCity.setText(null);
        }
    }//GEN-LAST:event_txtcityKeyReleased

    private void txtpasswordKeyReleased(java.awt.event.KeyEvent evt) {//GEN-FIRST:event_txtpasswordKeyReleased
        // TODO add your handling code here:
          String PATTERN = "^(?=.*[0-9])"
                       + "(?=.*[a-z])(?=.*[A-Z])"
                       + "(?=.*[@#$%^&+=])"
                       + "(?=\\S+$).{8,20}$"; // regex that matches the input
        Pattern pattern = Pattern.compile(PATTERN);
        Matcher match = pattern.matcher(txtpassword.getText()); // gets text from field and matched against the regex
     
        if(!match.matches())
        {
            checkError = "error";
            lblErrorPassword.setText("Make sure the password has atleast one number , a capital letter and a special character"); //throws message if input other than text is entered
        }
        else
        {
            checkError = null;
            lblErrorPassword.setText(null);
        }
    }//GEN-LAST:event_txtpasswordKeyReleased

    private void txtnameActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_txtnameActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_txtnameActionPerformed

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
        // TODO add your handling code here:
        
        int selectedRowIndex = tblperson.getSelectedRow();  // gives index of selected rows
        if(selectedRowIndex < 0)
        {
           JOptionPane.showMessageDialog(this, "Select a entry to view");
           return;
        }
        


          
        txtname1.setText(patientHistory.getPatientHistory().get(selectedRowIndex).getName());
        txtage1.setText(String.valueOf(patientHistory.getPatientHistory().get(selectedRowIndex).getAge()));
        txtphone1.setText(String.valueOf(patientHistory.getPatientHistory().get(selectedRowIndex).getPhone()));
        txthouseaddress1.setText(patientHistory.getPatientHistory().get(selectedRowIndex).getHouse());
        cbcommunity1.setSelectedItem(patientHistory.getPatientHistory().get(selectedRowIndex).getCommunityName());
        txtcity1.setText(patientHistory.getPatientHistory().get(selectedRowIndex).getCity());
        txtusername1.setText(patientHistory.getPatientHistory().get(selectedRowIndex).getUserName());
        txtpassword1.setText(patientHistory.getPatientHistory().get(selectedRowIndex).getPassword());


    }//GEN-LAST:event_jButton1ActionPerformed

    private void jTabbedPane1MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jTabbedPane1MouseClicked
        // TODO add your handling code here:
        
    }//GEN-LAST:event_jTabbedPane1MouseClicked

    private void cbcommunityActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbcommunityActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_cbcommunityActionPerformed

    private void btndeleteActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btndeleteActionPerformed
        // TODO add your handling code here:
         int selectedRowIndex = tblperson.getSelectedRow();  // gives index of selected rows
        if(selectedRowIndex < 0)
        {
           JOptionPane.showMessageDialog(this, "Select a entry to delete");
           return;
        }
        
                DefaultTableModel model = (DefaultTableModel)tblperson.getModel();
                Patient selectedEntry = patientHistory.getPatientHistory().get(selectedRowIndex);
                patientHistory.deletePatient(selectedEntry);
                
        JOptionPane.showMessageDialog(this, "Selected Employee Deleted");
         populateDataToTable(); //  deletes record from table and updates all entries

         



    }//GEN-LAST:event_btndeleteActionPerformed

    
    

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton btnadd;
    private javax.swing.JButton btndelete;
    private javax.swing.JButton btnupdate;
    private javax.swing.JComboBox<String> cbcommunity;
    private javax.swing.JComboBox<String> cbcommunity1;
    private javax.swing.JButton jButton1;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JTabbedPane jTabbedPane1;
    private javax.swing.JTextField jTextField1;
    private javax.swing.JTextField jTextField2;
    private javax.swing.JLabel lblAddTitle;
    private javax.swing.JLabel lblErrorAge;
    private javax.swing.JLabel lblErrorCity;
    private javax.swing.JLabel lblErrorHouseAddress;
    private javax.swing.JLabel lblErrorName;
    private javax.swing.JLabel lblErrorPassword;
    private javax.swing.JLabel lblErrorPhone;
    private javax.swing.JLabel lblErrorUserName;
    private javax.swing.JLabel lblage;
    private javax.swing.JLabel lblage1;
    private javax.swing.JLabel lblcity;
    private javax.swing.JLabel lblcity1;
    private javax.swing.JLabel lblcommunity;
    private javax.swing.JLabel lblcommunity1;
    private javax.swing.JLabel lblhouseaddress;
    private javax.swing.JLabel lblhouseaddress1;
    private javax.swing.JLabel lblname;
    private javax.swing.JLabel lblname1;
    private javax.swing.JLabel lblpassword;
    private javax.swing.JLabel lblpassword1;
    private javax.swing.JLabel lblphone;
    private javax.swing.JLabel lblphone1;
    private javax.swing.JLabel lbltitle;
    private javax.swing.JLabel lblusername;
    private javax.swing.JLabel lblusername1;
    private javax.swing.JScrollPane spperson;
    private javax.swing.JTable tblperson;
    private javax.swing.JTextField txtage;
    private javax.swing.JTextField txtage1;
    private javax.swing.JTextField txtcity;
    private javax.swing.JTextField txtcity1;
    private javax.swing.JTextField txthouseaddress;
    private javax.swing.JTextField txthouseaddress1;
    private javax.swing.JTextField txtname;
    private javax.swing.JTextField txtname1;
    private javax.swing.JTextField txtpassword;
    private javax.swing.JTextField txtpassword1;
    private javax.swing.JTextField txtphone;
    private javax.swing.JTextField txtphone1;
    private javax.swing.JTextField txtusername;
    private javax.swing.JTextField txtusername1;
    // End of variables declaration//GEN-END:variables

  private void populateDataToTable() {
        //TableModel is used to manipulate table content.
        // type casts tablemodel to defaultTableModel.
    DefaultTableModel model = (DefaultTableModel) tblperson.getModel();
    model.setRowCount(0); // deleting empty records
    
    // looping over profileHistory of employees.
    // getProfileHistory returns the history of employee records.
    for (Patient p : patientHistory.getPatientHistory()){
        
        // row is array of objects with 9 menbers. (1 for each column)
        Object[] row =  new Object[10];
        row[0] = p.getPatientId()/*.getPatientId()*/;/*.getEmployeeId()*/
        row[1] = p.getName();
        row[2] = p.getAge();
        row[3] = p.getPhone();
        row[4] = p.getCommunityName();
        row[5] = p.getHouse();
        row[6] = p.getCity();
        row[7] = p.getUserName();
        row[8] = p.getPassword();
                
        

        model.addRow(row); // adds row to model

    }
    }

}
