/*
 * Click nbfs://nbhost/SystemFileSystem/Templates/Licenses/license-default.txt to change this license
 * Click nbfs://nbhost/SystemFileSystem/Templates/GUIForms/JFrame.java to edit this template
 */
package ui;

import java.awt.CardLayout;
import medicalresourcemanagement.City;
import medicalresourcemanagement.CityDirectory;
import medicalresourcemanagement.Community;
import medicalresourcemanagement.CommunityDirectory;
import medicalresourcemanagement.Doctor;
import medicalresourcemanagement.DoctorDirectory;
import medicalresourcemanagement.Encounter;
import medicalresourcemanagement.EncounterHistory;
import medicalresourcemanagement.Hospital;
import medicalresourcemanagement.HospitalDirectory;
import medicalresourcemanagement.Patient;
import medicalresourcemanagement.PatientDirectory;



/**
 *
 * @author bhargavi
 */
public class SystemAdminView extends javax.swing.JFrame {

    Patient patient;
    PatientDirectory patientHistory; // declaring a class with some variable which has data type of class
    
    Hospital hospital;
    HospitalDirectory hospitalHistory;
    
    Doctor doctor;
    DoctorDirectory doctorHistory;
    
    Encounter encounter;
    EncounterHistory encounterHistory;
    
    Community community;
    CommunityDirectory communityHistory;
    
    City city;
    CityDirectory cityHistory;
//    JPanel workArea;
    
    
//    Encounter encounter;
    
    

    /**
     * Creates new form MainJFrame
     */
    public SystemAdminView(PatientDirectory patientHistory, DoctorDirectory doctorHistory,EncounterHistory encounterHistory, CityDirectory cityHistory, CommunityDirectory communityHistory) {
        initComponents();
        
//        encounter = new Encounter();
        this.patientHistory = patientHistory;
//        if(doctorHistory.getDoctorHistory().size() != 0 ){
//            this.doctorHistory = doctorHistory;
//        }
//        else {
            this.doctorHistory = new DoctorDirectory();
        
        this.encounterHistory = encounterHistory;
//        this.hospitalHistory = hospitalHistory;
        this.communityHistory = communityHistory;
        this.cityHistory = cityHistory;
        
//        this.patient = patient;
//        this.workArea = workArea;  

    }
    

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jToolBar1 = new javax.swing.JToolBar();
        splitPane = new javax.swing.JSplitPane();
        controlPanel = new javax.swing.JPanel();
        addPersonBtn = new javax.swing.JButton();
        btnManageDoctor = new javax.swing.JButton();
        Community = new javax.swing.JButton();
        btnManageHospital = new javax.swing.JButton();
        btnManageEncounter = new javax.swing.JButton();
        btnLogout = new javax.swing.JButton();
        workArea = new javax.swing.JPanel();

        jToolBar1.setRollover(true);

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setPreferredSize(new java.awt.Dimension(1500, 1000));

        splitPane.setPreferredSize(new java.awt.Dimension(1500, 700));

        controlPanel.setBackground(new java.awt.Color(204, 204, 204));
        controlPanel.setMinimumSize(new java.awt.Dimension(200, 600));
        controlPanel.setPreferredSize(new java.awt.Dimension(100, 1000));

        addPersonBtn.setText("Manage Patient");
        addPersonBtn.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                addPersonBtnActionPerformed(evt);
            }
        });

        btnManageDoctor.setText("Manage Doctor");
        btnManageDoctor.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageDoctorActionPerformed(evt);
            }
        });

        Community.setText("Community");

        btnManageHospital.setText("Manage Hospital");
        btnManageHospital.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageHospitalActionPerformed(evt);
            }
        });

        btnManageEncounter.setText("Manage Encounter");
        btnManageEncounter.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnManageEncounterActionPerformed(evt);
            }
        });

        btnLogout.setText("Logout");
        btnLogout.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnLogoutActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout controlPanelLayout = new javax.swing.GroupLayout(controlPanel);
        controlPanel.setLayout(controlPanelLayout);
        controlPanelLayout.setHorizontalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addContainerGap()
                .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING, false)
                        .addComponent(btnManageDoctor, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(Community, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnManageHospital, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(addPersonBtn, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                        .addComponent(btnManageEncounter, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addComponent(btnLogout, javax.swing.GroupLayout.PREFERRED_SIZE, 118, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(56, Short.MAX_VALUE))
        );

        controlPanelLayout.linkSize(javax.swing.SwingConstants.HORIZONTAL, new java.awt.Component[] {Community, addPersonBtn, btnManageDoctor, btnManageHospital});

        controlPanelLayout.setVerticalGroup(
            controlPanelLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(controlPanelLayout.createSequentialGroup()
                .addGap(224, 224, 224)
                .addComponent(addPersonBtn)
                .addGap(18, 18, 18)
                .addComponent(btnManageDoctor)
                .addGap(18, 18, 18)
                .addComponent(Community)
                .addGap(18, 18, 18)
                .addComponent(btnManageHospital)
                .addGap(18, 18, 18)
                .addComponent(btnManageEncounter)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, 232, Short.MAX_VALUE)
                .addComponent(btnLogout)
                .addGap(34, 34, 34))
        );

        splitPane.setLeftComponent(controlPanel);

        workArea.setPreferredSize(new java.awt.Dimension(1400, 1000));

        javax.swing.GroupLayout workAreaLayout = new javax.swing.GroupLayout(workArea);
        workArea.setLayout(workAreaLayout);
        workAreaLayout.setHorizontalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 1295, Short.MAX_VALUE)
        );
        workAreaLayout.setVerticalGroup(
            workAreaLayout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGap(0, 700, Short.MAX_VALUE)
        );

        splitPane.setRightComponent(workArea);

        javax.swing.GroupLayout layout = new javax.swing.GroupLayout(getContentPane());
        getContentPane().setLayout(layout);
        layout.setHorizontalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );
        layout.setVerticalGroup(
            layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(splitPane, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
        );

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void addPersonBtnActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_addPersonBtnActionPerformed
        // TODO add your handling code here:
        AddPatient addPerson = new AddPatient(workArea, patientHistory,  doctorHistory, encounterHistory,  cityHistory,  communityHistory);
        workArea.add("AddPatient", addPerson);
//         CardLayout cardlayout = (CardLayout) workArea.getLayout();
//        cardlayout.next(workArea);

                splitPane.setRightComponent(addPerson);

        
       
    }//GEN-LAST:event_addPersonBtnActionPerformed

    private void btnManageDoctorActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageDoctorActionPerformed
        // TODO add your handling code here:
        AddDoctor ad = new AddDoctor(workArea, patientHistory,  doctorHistory, encounterHistory,  cityHistory, communityHistory);
//        splitPane.setVisible(true);
        workArea.add("AddPatient", ad);
//         CardLayout cardlayout = (CardLayout) workArea.getLayout();
//        cardlayout.next(workArea);
                splitPane.setRightComponent(ad);

    }//GEN-LAST:event_btnManageDoctorActionPerformed

    private void btnManageHospitalActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageHospitalActionPerformed
        // TODO add your handling code here:
//        AddHospital addHospital = new AddHospital(hospitalHistory);
//        splitPane.setRightComponent(addHospital);


        manageHospitaljPanel mhjp = new manageHospitaljPanel(cityHistory, communityHistory,hospitalHistory);
//        splitPane.setVisible(true);
        workArea.add("Manage Hospital", mhjp);
//         CardLayout cardlayout = (CardLayout) workArea.getLayout();
//        cardlayout.next(workArea);
                splitPane.setRightComponent(mhjp);
    }//GEN-LAST:event_btnManageHospitalActionPerformed

    private void btnManageEncounterActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnManageEncounterActionPerformed
        // TODO add your handling code here:
        
        manageEncounterjPanel mejp = new manageEncounterjPanel(workArea,patientHistory,patient,encounterHistory);
        splitPane.setRightComponent(mejp);
        
    }//GEN-LAST:event_btnManageEncounterActionPerformed

    private void btnLogoutActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnLogoutActionPerformed
        // TODO add your handling code here:
        
//        MainJFrame mjf = new MainJFrame(patientHistory,communityHistory, cityHistory,doctorHistory,encounterHistory, hospitalHistory);
//        mjf.setVisible(true);
        this.setVisible(false);
        MainJFrame mjf = new MainJFrame( patientHistory,  doctorHistory, encounterHistory,  cityHistory,  communityHistory);

        mjf.setVisible(true);
    }//GEN-LAST:event_btnLogoutActionPerformed

//    /**
//     * @param args the command line arguments
//     */
//    public static void main(String args[]) {
//        /* Set the Nimbus look and feel */
//        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
//        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
//         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
//         */
//        try {
//            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
//                if ("Nimbus".equals(info.getName())) {
//                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
//                    break;
//                }
//            }
//        } catch (ClassNotFoundException ex) {
//            java.util.logging.Logger.getLogger(SystemAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (InstantiationException ex) {
//            java.util.logging.Logger.getLogger(SystemAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (IllegalAccessException ex) {
//            java.util.logging.Logger.getLogger(SystemAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
//            java.util.logging.Logger.getLogger(SystemAdminView.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
//        }
//        //</editor-fold>
//        //</editor-fold>
//
//        /* Create and display the form */
//        java.awt.EventQueue.invokeLater(new Runnable() {
//            public void run() {
//                new SystemAdminView(Patient patientHistory,DoctorDirectory doctorHistory,EncounterHistory encounterHistory,HospitalDirectory hospitalHistory).setVisible(true);
//            }
//        });
//    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton Community;
    private javax.swing.JButton addPersonBtn;
    private javax.swing.JButton btnLogout;
    private javax.swing.JButton btnManageDoctor;
    private javax.swing.JButton btnManageEncounter;
    private javax.swing.JButton btnManageHospital;
    private javax.swing.JPanel controlPanel;
    private javax.swing.JToolBar jToolBar1;
    private javax.swing.JSplitPane splitPane;
    private javax.swing.JPanel workArea;
    // End of variables declaration//GEN-END:variables
}
